# Generated by Django 5.0.7 on 2024-07-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('original_name', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('torrent_720', models.URLField(blank=True, null=True)),
                ('torrent_1080', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
