# Generated by Django 5.0.7 on 2024-07-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
