# Generated by Django 5.0.7 on 2024-07-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_keyword_1_movie_keyword_2_movie_keyword_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='keyword_4',
        ),
    ]
