# Generated by Django 5.0.7 on 2024-07-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_keyword_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
