# Generated by Django 5.0.7 on 2024-07-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keyword_4',
            field=models.CharField(blank=True, choices=[('series', 'Séries'), ('filmes', 'Filmes')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keyword_1',
            field=models.CharField(blank=True, choices=[('acao', 'Ação'), ('romance', 'Romance'), ('drama', 'Drama'), ('comedia', 'Comédia'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('ficcao_cientifica', 'Ficção Científica'), ('aventura', 'Aventura'), ('documentario', 'Documentário'), ('animacao', 'Animação'), ('musical', 'Musical'), ('biografia', 'Biografia'), ('historia', 'História'), ('guerra', 'Guerra'), ('misterio', 'Mistério'), ('policial', 'Policial'), ('western', 'Western'), ('familia', 'Família'), ('esporte', 'Esporte')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keyword_2',
            field=models.CharField(blank=True, choices=[('acao', 'Ação'), ('romance', 'Romance'), ('drama', 'Drama'), ('comedia', 'Comédia'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('ficcao_cientifica', 'Ficção Científica'), ('aventura', 'Aventura'), ('documentario', 'Documentário'), ('animacao', 'Animação'), ('musical', 'Musical'), ('biografia', 'Biografia'), ('historia', 'História'), ('guerra', 'Guerra'), ('misterio', 'Mistério'), ('policial', 'Policial'), ('western', 'Western'), ('familia', 'Família'), ('esporte', 'Esporte')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keyword_3',
            field=models.CharField(blank=True, choices=[('acao', 'Ação'), ('romance', 'Romance'), ('drama', 'Drama'), ('comedia', 'Comédia'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('ficcao_cientifica', 'Ficção Científica'), ('aventura', 'Aventura'), ('documentario', 'Documentário'), ('animacao', 'Animação'), ('musical', 'Musical'), ('biografia', 'Biografia'), ('historia', 'História'), ('guerra', 'Guerra'), ('misterio', 'Mistério'), ('policial', 'Policial'), ('western', 'Western'), ('familia', 'Família'), ('esporte', 'Esporte')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
